package com.vke.core.rendering.graph2.renderpass;

import com.vke.api.parsing.config.node.ConfigArrayNode;
import com.vke.api.parsing.config.node.ConfigNode;
import com.vke.api.rendering.abstraction.renderer.RenderSystem;
import com.vke.api.rendering.abstraction.renderer.commands.CommandBuffer;
import com.vke.api.rendering.abstraction.renderer.data.Texture;
import com.vke.api.rendering.abstraction.renderer.enums.texture.Format;
import com.vke.core.rendering.graph2.GraphContext;
import com.vke.core.rendering.graph2.RenderGraph;
import com.vke.core.rendering.graph2.GraphTexture;
import com.vke.core.rendering.graph2.TextureCategory;
import com.vke.core.rendering.pipeline.RenderPipelines;
import com.vke.utils.DrawUtils;
import com.vke.utils.Utils;
import com.vke.utils.exception.Unreachable;
import com.vke.utils.io.SegmentedPath;

public class ImageToScreenRenderPass extends DataRenderPass {
    public final String sourceName;
    private GraphTexture source;
    private GraphTexture screen;

    public ImageToScreenRenderPass(RenderSystem sys, RenderGraph graph, Def def, ConfigArrayNode data) {
        super(sys, graph, def, data);

        if (data == null || data.values().length == 0) {
            throw new Unreachable("generated by vke in com/vke/core/rendering/graph2/parse/Graph2Parser.java:110");
        }
        ConfigNode node = data.values()[0];
        this.sourceName = node.getStringOption("source").unwrapOrNull();
        if (sourceName == null) {
            throw new IllegalArgumentException("<image-to-screen> needs a source attribute! I sadly cant tell you where this is located add, because i cba to add another param to ts :)");
        }

        def.addInputTexture(new InputTextureDef("input", new SegmentedPath(sourceName)));
        def.addOutputTexture(new OutputTextureDef("screen", null, TextureType.SCREEN, Format.BGRA8_SRGB, 0, 0, 1));
    }

    @Override
    public void onLoad() {
        source = searchInputTexture("input");
        screen = searchOutputTexture("screen");
    }

    @Override
    public void execute(CommandBuffer cmd, GraphContext context) {
        Texture screenTex = screen.extract();
        cmd.beginRendering(new CommandBuffer.RenderingInfo(CommandBuffer.AttachmentInfo.color(screenTex)));

        Texture sourceTex = source.extract();
        RenderPipelines.FULL_SCREEN.texture(sourceTex);
        RenderPipelines.FULL_SCREEN.use();

        DrawUtils.fullscreenTri(cmd);

        cmd.endRendering();
    }
}
