package com.vke.api.rendering.vulkan;

import com.vke.api.rendering.abstraction.renderer.IntEnum;
import org.lwjgl.vulkan.KHRSwapchain;
import org.lwjgl.vulkan.VK14;

public enum ImageLayout implements IntEnum {

    UNDEFINED(VK14.VK_IMAGE_LAYOUT_UNDEFINED),
    GENERAL(VK14.VK_IMAGE_LAYOUT_GENERAL),
    COLOR_ATTACHMENT_OPTIMAL(VK14.VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL),
    DEPTH_STENCIL_ATTACHMENT_OPTIMAL(VK14.VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL),
    DEPTH_STENCIL_READONLY_OPTIMAL(VK14.VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL),
    SHADER_READONLY_OPTIMAL(VK14.VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL),
    TRANSFER_SRC_OPTIMAL(VK14.VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL),
    TRANSFER_DST_OPTIMAL(VK14.VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL),
    PREINITIALIZED(VK14.VK_IMAGE_LAYOUT_PREINITIALIZED),

    PRESENT_SRC_KHR(KHRSwapchain.VK_IMAGE_LAYOUT_PRESENT_SRC_KHR);

    private final int vkHandle;

    ImageLayout(int handle) {
        this.vkHandle = handle;
    }

    @Override
    public int getIntVal() {
        return vkHandle;
    }
}
